export const WIN_SENTENCES = [
  "You won!",
  "Great work!",
  "Fantastic!",
  "Amazing!",
  "Terrific!",
  "Awesome!",
  "Incredible!",
  "Unbelievable!",
  "Stupendous!",
  "Spectacular!",
  "Marvelous!",
  "Astounding!",
  "Stunning!",
  "Magnificent!",
  "Superb!",
  "Breathtaking!",
  "Phenomenal!",
  "Extraordinary!",
  "Mind-blowing!",
  "Outstanding!"
];
